# Generated by Django 4.1.4 on 2023-02-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_offers_dicount_alter_offers_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='dicount',
            new_name='discount',
        ),
    ]
